'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Lettera
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * KSF Media's articles service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * The version of the OpenAPI document: 2.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _ArticleType = require('./ArticleType');

var _ArticleType2 = _interopRequireDefault(_ArticleType);

var _ArticleTypeDetails = require('./ArticleTypeDetails');

var _ArticleTypeDetails2 = _interopRequireDefault(_ArticleTypeDetails);

var _Author = require('./Author');

var _Author2 = _interopRequireDefault(_Author);

var _Block = require('./Block');

var _Block2 = _interopRequireDefault(_Block);

var _ImageInfo = require('./ImageInfo');

var _ImageInfo2 = _interopRequireDefault(_ImageInfo);

var _Paper = require('./Paper');

var _Paper2 = _interopRequireDefault(_Paper);

var _RelatedArticle = require('./RelatedArticle');

var _RelatedArticle2 = _interopRequireDefault(_RelatedArticle);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The Article model module.
 * @module model/Article
 * @version 2.0.0
 */
var Article = function () {
  /**
   * Constructs a new <code>Article</code>.
   * @alias module:model/Article
   * @param uuid {String} 
   * @param title {String} 
   * @param authors {Array.<module:model/Author>} 
   * @param tags {Array.<String>} 
   * @param body {Array.<module:model/Block>} 
   * @param premium {Boolean} 
   * @param publishingTime {String} 
   * @param articleType {module:model/ArticleType} 
   * @param relatedArticles {Array.<module:model/RelatedArticle>} 
   * @param paper {module:model/Paper} 
   */
  function Article(uuid, title, authors, tags, body, premium, publishingTime, articleType, relatedArticles, paper) {
    _classCallCheck(this, Article);

    Article.initialize(this, uuid, title, authors, tags, body, premium, publishingTime, articleType, relatedArticles, paper);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(Article, null, [{
    key: 'initialize',
    value: function initialize(obj, uuid, title, authors, tags, body, premium, publishingTime, articleType, relatedArticles, paper) {
      obj['uuid'] = uuid;
      obj['title'] = title;
      obj['authors'] = authors;
      obj['tags'] = tags;
      obj['body'] = body;
      obj['premium'] = premium;
      obj['publishingTime'] = publishingTime;
      obj['articleType'] = articleType;
      obj['relatedArticles'] = relatedArticles;
      obj['paper'] = paper;
    }

    /**
     * Constructs a <code>Article</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Article} obj Optional instance to populate.
     * @return {module:model/Article} The populated <code>Article</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new Article();

        if (data.hasOwnProperty('uuid')) {
          obj['uuid'] = _ApiClient2.default.convertToType(data['uuid'], 'String');
        }
        if (data.hasOwnProperty('title')) {
          obj['title'] = _ApiClient2.default.convertToType(data['title'], 'String');
        }
        if (data.hasOwnProperty('authors')) {
          obj['authors'] = _ApiClient2.default.convertToType(data['authors'], [_Author2.default]);
        }
        if (data.hasOwnProperty('tags')) {
          obj['tags'] = _ApiClient2.default.convertToType(data['tags'], ['String']);
        }
        if (data.hasOwnProperty('preamble')) {
          obj['preamble'] = _ApiClient2.default.convertToType(data['preamble'], 'String');
        }
        if (data.hasOwnProperty('mainImage')) {
          obj['mainImage'] = _ImageInfo2.default.constructFromObject(data['mainImage']);
        }
        if (data.hasOwnProperty('listImage')) {
          obj['listImage'] = _ImageInfo2.default.constructFromObject(data['listImage']);
        }
        if (data.hasOwnProperty('body')) {
          obj['body'] = _ApiClient2.default.convertToType(data['body'], [_Block2.default]);
        }
        if (data.hasOwnProperty('premium')) {
          obj['premium'] = _ApiClient2.default.convertToType(data['premium'], 'Boolean');
        }
        if (data.hasOwnProperty('publishingTime')) {
          obj['publishingTime'] = _ApiClient2.default.convertToType(data['publishingTime'], 'String');
        }
        if (data.hasOwnProperty('updateTime')) {
          obj['updateTime'] = _ApiClient2.default.convertToType(data['updateTime'], 'String');
        }
        if (data.hasOwnProperty('articleType')) {
          obj['articleType'] = _ArticleType2.default.constructFromObject(data['articleType']);
        }
        if (data.hasOwnProperty('articleTypeDetails')) {
          obj['articleTypeDetails'] = _ArticleTypeDetails2.default.constructFromObject(data['articleTypeDetails']);
        }
        if (data.hasOwnProperty('externalScripts')) {
          obj['externalScripts'] = _ApiClient2.default.convertToType(data['externalScripts'], ['String']);
        }
        if (data.hasOwnProperty('relatedArticles')) {
          obj['relatedArticles'] = _ApiClient2.default.convertToType(data['relatedArticles'], [_RelatedArticle2.default]);
        }
        if (data.hasOwnProperty('shareUrl')) {
          obj['shareUrl'] = _ApiClient2.default.convertToType(data['shareUrl'], 'String');
        }
        if (data.hasOwnProperty('paper')) {
          obj['paper'] = _Paper2.default.constructFromObject(data['paper']);
        }
        if (data.hasOwnProperty('analyticsCategory')) {
          obj['analyticsCategory'] = _ApiClient2.default.convertToType(data['analyticsCategory'], 'String');
        }
        if (data.hasOwnProperty('analyticsSection')) {
          obj['analyticsSection'] = _ApiClient2.default.convertToType(data['analyticsSection'], 'String');
        }
        if (data.hasOwnProperty('articlePriority')) {
          obj['articlePriority'] = _ApiClient2.default.convertToType(data['articlePriority'], 'Number');
        }
      }
      return obj;
    }
  }]);

  return Article;
}();

/**
 * @member {String} uuid
 */


Article.prototype['uuid'] = undefined;

/**
 * @member {String} title
 */
Article.prototype['title'] = undefined;

/**
 * @member {Array.<module:model/Author>} authors
 */
Article.prototype['authors'] = undefined;

/**
 * @member {Array.<String>} tags
 */
Article.prototype['tags'] = undefined;

/**
 * @member {String} preamble
 */
Article.prototype['preamble'] = undefined;

/**
 * @member {module:model/ImageInfo} mainImage
 */
Article.prototype['mainImage'] = undefined;

/**
 * @member {module:model/ImageInfo} listImage
 */
Article.prototype['listImage'] = undefined;

/**
 * @member {Array.<module:model/Block>} body
 */
Article.prototype['body'] = undefined;

/**
 * @member {Boolean} premium
 */
Article.prototype['premium'] = undefined;

/**
 * @member {String} publishingTime
 */
Article.prototype['publishingTime'] = undefined;

/**
 * @member {String} updateTime
 */
Article.prototype['updateTime'] = undefined;

/**
 * @member {module:model/ArticleType} articleType
 */
Article.prototype['articleType'] = undefined;

/**
 * @member {module:model/ArticleTypeDetails} articleTypeDetails
 */
Article.prototype['articleTypeDetails'] = undefined;

/**
 * @member {Array.<String>} externalScripts
 */
Article.prototype['externalScripts'] = undefined;

/**
 * @member {Array.<module:model/RelatedArticle>} relatedArticles
 */
Article.prototype['relatedArticles'] = undefined;

/**
 * @member {String} shareUrl
 */
Article.prototype['shareUrl'] = undefined;

/**
 * @member {module:model/Paper} paper
 */
Article.prototype['paper'] = undefined;

/**
 * @member {String} analyticsCategory
 */
Article.prototype['analyticsCategory'] = undefined;

/**
 * @member {String} analyticsSection
 */
Article.prototype['analyticsSection'] = undefined;

/**
 * @member {Number} articlePriority
 */
Article.prototype['articlePriority'] = undefined;

exports.default = Article;