'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Lettera
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * KSF Media's articles service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * The version of the OpenAPI document: 2.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _BoxInfo = require('./BoxInfo');

var _BoxInfo2 = _interopRequireDefault(_BoxInfo);

var _ImageInfo = require('./ImageInfo');

var _ImageInfo2 = _interopRequireDefault(_ImageInfo);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The Block model module.
 * @module model/Block
 * @version 2.0.0
 */
var Block = function () {
  /**
   * Constructs a new <code>Block</code>.
   * @alias module:model/Block
   */
  function Block() {
    _classCallCheck(this, Block);

    Block.initialize(this);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(Block, null, [{
    key: 'initialize',
    value: function initialize(obj) {}

    /**
     * Constructs a <code>Block</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Block} obj Optional instance to populate.
     * @return {module:model/Block} The populated <code>Block</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new Block();

        if (data.hasOwnProperty('paragraph')) {
          obj['paragraph'] = _ApiClient2.default.convertToType(data['paragraph'], 'String');
        }
        if (data.hasOwnProperty('html')) {
          obj['html'] = _ApiClient2.default.convertToType(data['html'], 'String');
        }
        if (data.hasOwnProperty('image')) {
          obj['image'] = _ImageInfo2.default.constructFromObject(data['image']);
        }
        if (data.hasOwnProperty('box')) {
          obj['box'] = _BoxInfo2.default.constructFromObject(data['box']);
        }
        if (data.hasOwnProperty('headline')) {
          obj['headline'] = _ApiClient2.default.convertToType(data['headline'], 'String');
        }
        if (data.hasOwnProperty('footnote')) {
          obj['footnote'] = _ApiClient2.default.convertToType(data['footnote'], 'String');
        }
        if (data.hasOwnProperty('question')) {
          obj['question'] = _ApiClient2.default.convertToType(data['question'], 'String');
        }
        if (data.hasOwnProperty('quote')) {
          obj['quote'] = _ApiClient2.default.convertToType(data['quote'], 'String');
        }
      }
      return obj;
    }
  }]);

  return Block;
}();

/**
 * @member {String} paragraph
 */


Block.prototype['paragraph'] = undefined;

/**
 * @member {String} html
 */
Block.prototype['html'] = undefined;

/**
 * @member {module:model/ImageInfo} image
 */
Block.prototype['image'] = undefined;

/**
 * @member {module:model/BoxInfo} box
 */
Block.prototype['box'] = undefined;

/**
 * @member {String} headline
 */
Block.prototype['headline'] = undefined;

/**
 * @member {String} footnote
 */
Block.prototype['footnote'] = undefined;

/**
 * @member {String} question
 */
Block.prototype['question'] = undefined;

/**
 * @member {String} quote
 */
Block.prototype['quote'] = undefined;

exports.default = Block;