'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Lettera
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * KSF Media's articles service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * The version of the OpenAPI document: 2.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _BoxType = require('./BoxType');

var _BoxType2 = _interopRequireDefault(_BoxType);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The BoxInfo model module.
 * @module model/BoxInfo
 * @version 2.0.0
 */
var BoxInfo = function () {
  /**
   * Constructs a new <code>BoxInfo</code>.
   * @alias module:model/BoxInfo
   * @param title {String} 
   * @param content {Array.<String>} 
   * @param type {module:model/BoxType} 
   */
  function BoxInfo(title, content, type) {
    _classCallCheck(this, BoxInfo);

    BoxInfo.initialize(this, title, content, type);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(BoxInfo, null, [{
    key: 'initialize',
    value: function initialize(obj, title, content, type) {
      obj['title'] = title;
      obj['content'] = content;
      obj['type'] = type;
    }

    /**
     * Constructs a <code>BoxInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BoxInfo} obj Optional instance to populate.
     * @return {module:model/BoxInfo} The populated <code>BoxInfo</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new BoxInfo();

        if (data.hasOwnProperty('title')) {
          obj['title'] = _ApiClient2.default.convertToType(data['title'], 'String');
        }
        if (data.hasOwnProperty('headline')) {
          obj['headline'] = _ApiClient2.default.convertToType(data['headline'], 'String');
        }
        if (data.hasOwnProperty('content')) {
          obj['content'] = _ApiClient2.default.convertToType(data['content'], ['String']);
        }
        if (data.hasOwnProperty('type')) {
          obj['type'] = _BoxType2.default.constructFromObject(data['type']);
        }
      }
      return obj;
    }
  }]);

  return BoxInfo;
}();

/**
 * @member {String} title
 */


BoxInfo.prototype['title'] = undefined;

/**
 * @member {String} headline
 */
BoxInfo.prototype['headline'] = undefined;

/**
 * @member {Array.<String>} content
 */
BoxInfo.prototype['content'] = undefined;

/**
 * @member {module:model/BoxType} type
 */
BoxInfo.prototype['type'] = undefined;

exports.default = BoxInfo;