'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Lettera
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * KSF Media's articles service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * The version of the OpenAPI document: 2.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The Category model module.
 * @module model/Category
 * @version 2.0.0
 */
var Category = function () {
  /**
   * Constructs a new <code>Category</code>.
   * @alias module:model/Category
   * @param id {String} 
   * @param label {String} 
   * @param type {module:model/Category.TypeEnum} 
   */
  function Category(id, label, type) {
    _classCallCheck(this, Category);

    Category.initialize(this, id, label, type);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(Category, null, [{
    key: 'initialize',
    value: function initialize(obj, id, label, type) {
      obj['id'] = id;
      obj['label'] = label;
      obj['type'] = type;
    }

    /**
     * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Category} obj Optional instance to populate.
     * @return {module:model/Category} The populated <code>Category</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new Category();

        if (data.hasOwnProperty('id')) {
          obj['id'] = _ApiClient2.default.convertToType(data['id'], 'String');
        }
        if (data.hasOwnProperty('label')) {
          obj['label'] = _ApiClient2.default.convertToType(data['label'], 'String');
        }
        if (data.hasOwnProperty('type')) {
          obj['type'] = _ApiClient2.default.convertToType(data['type'], 'String');
        }
        if (data.hasOwnProperty('url')) {
          obj['url'] = _ApiClient2.default.convertToType(data['url'], 'String');
        }
        if (data.hasOwnProperty('subcategories')) {
          obj['subcategories'] = _ApiClient2.default.convertToType(data['subcategories'], [Category]);
        }
      }
      return obj;
    }
  }]);

  return Category;
}();

/**
 * @member {String} id
 */


Category.prototype['id'] = undefined;

/**
 * @member {String} label
 */
Category.prototype['label'] = undefined;

/**
 * @member {module:model/Category.TypeEnum} type
 */
Category.prototype['type'] = undefined;

/**
 * @member {String} url
 */
Category.prototype['url'] = undefined;

/**
 * @member {Array.<module:model/Category>} subcategories
 */
Category.prototype['subcategories'] = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Category['TypeEnum'] = {

  /**
   * value: "feed"
   * @const
   */
  "feed": "feed",

  /**
   * value: "webview"
   * @const
   */
  "webview": "webview",

  /**
   * value: "link"
   * @const
   */
  "link": "link"
};

exports.default = Category;