'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Lettera
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * KSF Media's articles service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * The version of the OpenAPI document: 2.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _Alignment = require('./Alignment');

var _Alignment2 = _interopRequireDefault(_Alignment);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The ImageInfo model module.
 * @module model/ImageInfo
 * @version 2.0.0
 */
var ImageInfo = function () {
  /**
   * Constructs a new <code>ImageInfo</code>.
   * @alias module:model/ImageInfo
   * @param url {String} 
   * @param thumb {String} 
   */
  function ImageInfo(url, thumb) {
    _classCallCheck(this, ImageInfo);

    ImageInfo.initialize(this, url, thumb);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(ImageInfo, null, [{
    key: 'initialize',
    value: function initialize(obj, url, thumb) {
      obj['url'] = url;
      obj['thumb'] = thumb;
    }

    /**
     * Constructs a <code>ImageInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImageInfo} obj Optional instance to populate.
     * @return {module:model/ImageInfo} The populated <code>ImageInfo</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new ImageInfo();

        if (data.hasOwnProperty('url')) {
          obj['url'] = _ApiClient2.default.convertToType(data['url'], 'String');
        }
        if (data.hasOwnProperty('thumb')) {
          obj['thumb'] = _ApiClient2.default.convertToType(data['thumb'], 'String');
        }
        if (data.hasOwnProperty('caption')) {
          obj['caption'] = _ApiClient2.default.convertToType(data['caption'], 'String');
        }
        if (data.hasOwnProperty('alignment')) {
          obj['alignment'] = _Alignment2.default.constructFromObject(data['alignment']);
        }
        if (data.hasOwnProperty('byline')) {
          obj['byline'] = _ApiClient2.default.convertToType(data['byline'], 'String');
        }
      }
      return obj;
    }
  }]);

  return ImageInfo;
}();

/**
 * @member {String} url
 */


ImageInfo.prototype['url'] = undefined;

/**
 * @member {String} thumb
 */
ImageInfo.prototype['thumb'] = undefined;

/**
 * @member {String} caption
 */
ImageInfo.prototype['caption'] = undefined;

/**
 * @member {module:model/Alignment} alignment
 */
ImageInfo.prototype['alignment'] = undefined;

/**
 * @member {String} byline
 */
ImageInfo.prototype['byline'] = undefined;

exports.default = ImageInfo;