'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Lettera
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * KSF Media's articles service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * The version of the OpenAPI document: 2.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://openapi-generator.tech
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _EventType = require('./EventType');

var _EventType2 = _interopRequireDefault(_EventType);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
 * The Notification model module.
 * @module model/Notification
 * @version 2.0.0
 */
var Notification = function () {
  /**
   * Constructs a new <code>Notification</code>.
   * @alias module:model/Notification
   * @param contentType {String} 
   * @param eventtype {module:model/EventType} 
   * @param uuid {String} 
   */
  function Notification(contentType, eventtype, uuid) {
    _classCallCheck(this, Notification);

    Notification.initialize(this, contentType, eventtype, uuid);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */


  _createClass(Notification, null, [{
    key: 'initialize',
    value: function initialize(obj, contentType, eventtype, uuid) {
      obj['contentType'] = contentType;
      obj['eventtype'] = eventtype;
      obj['uuid'] = uuid;
    }

    /**
     * Constructs a <code>Notification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Notification} obj Optional instance to populate.
     * @return {module:model/Notification} The populated <code>Notification</code> instance.
     */

  }, {
    key: 'constructFromObject',
    value: function constructFromObject(data, obj) {
      if (data) {
        obj = obj || new Notification();

        if (data.hasOwnProperty('contentType')) {
          obj['contentType'] = _ApiClient2.default.convertToType(data['contentType'], 'String');
        }
        if (data.hasOwnProperty('eventid')) {
          obj['eventid'] = _ApiClient2.default.convertToType(data['eventid'], 'Number');
        }
        if (data.hasOwnProperty('eventtype')) {
          obj['eventtype'] = _EventType2.default.constructFromObject(data['eventtype']);
        }
        if (data.hasOwnProperty('uuid')) {
          obj['uuid'] = _ApiClient2.default.convertToType(data['uuid'], 'String');
        }
      }
      return obj;
    }
  }]);

  return Notification;
}();

/**
 * @member {String} contentType
 */


Notification.prototype['contentType'] = undefined;

/**
 * @member {Number} eventid
 */
Notification.prototype['eventid'] = undefined;

/**
 * @member {module:model/EventType} eventtype
 */
Notification.prototype['eventtype'] = undefined;

/**
 * @member {String} uuid
 */
Notification.prototype['uuid'] = undefined;

exports.default = Notification;